config/routes.rb
Foodtruckrodeo::Application.routes.draw do

  resources :food_trucks

  root 'overview_map#index'

end

app/models/food_truck.rb
class FoodTruck < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/food_trucks_controller.rb
class FoodTrucksController < ApplicationController
  before_action :set_food_truck, only: [:show, :edit, :update, :destroy]

  # GET /food_trucks
  def index
    @food_trucks = FoodTruck.all
  end

  # GET /food_trucks/1
  def show
    @location = Gmaps4rails.build_markers(@food_truck) do |truck, marker|
      marker.lat  truck.latitude
      marker.lng  truck.longitude
      marker.infowindow truck.name
      #marker.picture ({
      #    url:  "food_truck.png",
      #    width:  49,
      #    height: 32
      #})
    end
  end

  # GET /food_trucks/new
  def new
    @food_truck = FoodTruck.new
  end

  # GET /food_trucks/1/edit
  def edit
  end

  # POST /food_trucks
  def create
    @food_truck = FoodTruck.new(food_truck_params)

    if @food_truck.save
      redirect_to @food_truck, notice: 'Food truck was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /food_trucks/1
  # PATCH/PUT /food_trucks/1.json
  def update
    if @food_truck.update(food_truck_params)
      redirect_to @food_truck, notice: 'Food truck was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /food_trucks/1
  # DELETE /food_trucks/1.json
  def destroy
    @food_truck.destroy
    redirect_to food_trucks_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_truck
      @food_truck = FoodTruck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_truck_params
      params.require(:food_truck).permit(:address, :name)
    end

end

app/controllers/overview_map_controller.rb
class OverviewMapController < ApplicationController

  RANGE = 50 #miles

  def index
  #  if user_location?
  #    @food_trucks = FoodTruck.near([user_latitude, user_longitude], RANGE)
  #  else
      @food_trucks = FoodTruck.where("latitude is not null").where("longitude is not null")
 #   end

    @locations = truck_location_places

   #   @locations << user_location_place if user_location?
  end

  private

  def user_location?
    cookies[:lat_lng] && cookies[:lat_lng].split("|").length == 2
  end

  def user_latitude
    cookie = cookies[:lat_lng].split("|")
    cookie[0]
  end

  def user_longitude
    cookie = cookies[:lat_lng].split("|")
    cookie[1]
  end

  def truck_location_places
    Gmaps4rails.build_markers(@food_trucks) do |truck, marker|
      marker.lat  truck.latitude
      marker.lng  truck.longitude
      marker.infowindow render_to_string(partial: "/food_trucks/infowindow", locals: { truck: truck} )
     # marker.picture ({
     #     url:  "food_truck.png",
     #     width:  49,
     #     height: 32
     # })
    end
  end

  def user_location_place
    Gmaps4rails.build_markers([cookies[:lat_lng].split("|")]) { |start, marker|
      marker.lat start[0]
      marker.lng start[1]
      marker.infowindow 'Start'
    }.first
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController


  def home;end

  def about; end
end

app/views/food_trucks/_form.html.haml
= form_for @food_truck do |f|
  - if @food_truck.errors.any?
    #error_explanation
      %h2= "#{pluralize(@food_truck.errors.count, "error")} prohibited this food_truck from being saved:"
      %ul
        - @food_truck.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :latitude
    = f.text_field :latitude
  .field
    = f.label :longitude
    = f.text_field :longitude

  .actions
    = f.submit 'Save'

app/views/food_trucks/_infowindow.html.haml
%p= link_to truck.name, food_truck_path(truck.id)

app/views/food_trucks/edit.html.haml
.container
  .row
    %h1 Editing food_truck

    = render 'form'

    = link_to 'Show', @food_truck
    \|
    = link_to 'Back', food_trucks_path

app/views/food_trucks/index.html.haml
.container
  .row
    %h1 Food Trucks

    %table.table.table-striped
      %tr
        %th Name
        %th Address
        %th Latitude
        %th Longitude
        %th
        %th
        %th

      - @food_trucks.each do |food_truck|
        %tr
          %td= food_truck.name
          %td= food_truck.address
          %td= food_truck.latitude
          %td= food_truck.longitude
          %td= link_to 'Show', food_truck
          %td= link_to 'Edit', edit_food_truck_path(food_truck)
          %td= link_to 'Destroy', food_truck, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br

    = link_to 'New Food Truck', new_food_truck_path

app/views/food_trucks/new.html.haml
.container
  .row
    %h1 New food_truck

    = render 'form'

    = link_to 'Back', food_trucks_path

app/views/food_trucks/show.html.haml
.container
  .row
    %p#notice= notice

    #truck

    %p
      %b Name:
      = @food_truck.name
    %p
      %b Address:
      = @food_truck.address
    %p
      %b Website:
      = @food_truck.url
    %p
      %b Latitude:
      = @food_truck.latitude
    %p
      %b Longitude:
      = @food_truck.longitude

    = link_to 'Edit', edit_food_truck_path(@food_truck)
    \|
    = link_to 'Food Trucks', food_trucks_path
    \|
    = link_to 'Home', root_path

    :javascript
      var the_markers = #{raw @location.to_json};
      $(document).ready(function(){ showTruck(the_markers); });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Food Truck Rodeo</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?v=3.23&libraries=geometry" type="text/javascript"></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
</head>
<body>
<div class="navigation">
  <%= link_to "Home", root_path %>
  |
  <%= link_to "Food Trucks", food_trucks_path %>
</div>
<%= yield %>

</body>
</html>

app/views/overview_map/index.html.haml
#map

:javascript
  var the_markers = #{raw @locations.to_json}
  $(document).ready(function(){

  showTrucks(the_markers);
  })